server:
  servlet:
    contextPath: /boraviajar
spring:
  profiles:
    active: '@activatedProperties@'
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: trail
      host: localhost
      port: 27017
